name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@v0.16.0
        with:
          app_id: ${{ secrets.APP_ID }}
          app_pem: ${{ secrets.APP_PEM }}
